
[server]
headless = true
port = 10000

[browser]
serverAddress = "0.0.0.0"
serverPort = 10000

[theme]
base="dark"  # Altere para "dark" se preferir o tema escuro
primaryColor="#1f77b4"
backgroundColor="#f0f2f6"
secondaryBackgroundColor="#e0e0e0"
textColor="#262730"